### ISSUE TITLE
Not added files of target plugin and target test runner plugin to plugin test bed

### ISSUE THREAD

**Issue by Hiroyuki-Anzai** [sony/generator-cordova-plugin-devbed#4]
問題を発見したため報告させていただきます。
- 現象
  Plugin test bed に これから作成するための Plugin や Test runner の Plugin のファイルがない。
  Cordova 的にはインストールはされている。
- 実行環境
  - Windows 7 Ultimate SP1
  - node : v0.10.40
  - git : version 1.9.5.msysgit.1
  - cordova : 5.1.1
  - generator-cordova-plugin-devbed : 0.2.0
- 詳細
  前提：各開発環境は構築済み
  - 手順1：以下のコマンドで generator-cordova-plugin-devbed をインストール
    
    ```
    >npm install -g generator-cordova-plugin-devbed
    ```
  - 手順2：以下のコマンドで Plugin test bed を作成開始
    
    ```
    >yo cordova-plugin-devbed
    ```
  - 手順3：各ユーザーインターラクションにて下記を入力
    
    ```
    ? Enter the name of plugin. ABCPlugin
    ? (他はデフォルトのまま、ただし Platforms で Android を指定)
    ```
  - 現象発生1：コンソールのログで `*** Adding target test runner plugin to plugin test bed **` 表示後にエラーログが表示（詳細は下記 Sanpshot 参照）
    ただし、処理は続行されコンソール上では成功したように終了する。
      ![console_error_snapshot](https://cloud.githubusercontent.com/assets/10624432/11676789/9f5e2452-9e79-11e5-81c0-7d5e61171d59.png)
  - 現象発生2：Test bed に対象の Plugin や Test runner の Plugin のファイルがない
    Cordova 的には対象の Plugin や Test runner の Plugin はインストールされたことになっている
      ![testbed_androidjson](https://cloud.githubusercontent.com/assets/10624432/11677060/bc6769f2-9e7c-11e5-915c-4ac6a88372b3.png)
    
    しかし、それらの Plugin のファイルが Test bed にない
      ![testbed_foldertree_snapshot](https://cloud.githubusercontent.com/assets/10624432/11676868/a3bb2b2a-9e7a-11e5-8b57-82daa9f94ed0.png)
    
    以下のようになっていることが望まれるのではないでしょうか？
    
    ```
      \ABCPlugin
      \ABCPlugin_TestBed
          \plugins
              \**
              \org.cool.abcplugin
              \org.cool.abcplugin-tests
    ```

**Comment by Hiroyuki-Anzai** [comment]
原因を調査しました。
- 根本的な原因
  [README.md](https://github.com/sony/generator-cordova-plugin-devbed/blob/master/README.md) に記載されている「generator の作業内容」の以下において
  
  ```
  ⅶ. アプリに plugin を追加
    先に作成した plugin をアプリに追加
    cordova plugin add 相当
  ⅷ. アプリにテスト plugin を追加
   cordova-plugin-test-framework で参照するテスト plugin をアプリに追加
  ```
  
  プログラム上で、Corodva plugin の追加をする際に指定する "先に作成した plugin" と "テスト plugin" のパスが間違っていることが原因のようです。
  - 詳細
    原因の generator-cordova-plugin-devbed ソースコードは以下となります。
    - _testbed_add_plugin\index.js
    - _testbed_add_test_plugin\index.js
    
    まず、上記それぞれが動作する際に `cordova_changedir: function()` がまず実行され `/ABCPlugin_TestBed フォルダー` に Change Directory されます。
    
    そして、 `cordova_add_platform: function()` にて、"Cordova" に対して Plugin を追加する要求を投げますが、その時に指定される Plugin のパスが以下のようになっています。
    - "先に作成した plugin" : ABCPlugin
    - "テスト plugin" : ABCPlugin/tests
    
    そのため、指定されたフォルダーが存在しない（または Plugin はない）のでエラーになっているようです。
    
    ```
    \ABCPlugin  //<- "先に作成した plugin" の指定先
        \src
        \tests         //<-  "テスト plugin" の指定先
            plugin.xml
            tests.js
        \www
        package.json
        plugin.xml
    \ABCPlugin_TestBed
        \**
    ```
    
    `/ABCPlugin_TestBed フォルダー` に Change Directory されているので本来であれば下記が正しいように思えます。
    - "先に作成した plugin" : ../ABCPlugin
    - "テスト plugin" : ../ABCPlugin/tests
    
    試しにインストールされた generator-cordova-plugin-devbed のソースコードをローカルで下記のように変更し実行したら想定通りの動作になりました。
    - _testbed_add_plugin\index.js の 37行目
      
      ```
      var plugins = [this.props.pluginName];
      ↓
      var plugins = ['../' + this.props.pluginName];
      ```
    - _testbed_add_test_plugin\index.js の 35行目
      
      ```
      var plugins = [this.props.pluginName+'/tests'];
      ↓
      var plugins = ['../' + this.props.pluginName+'/tests'];
      ```

**Comment by ahirun0426** [comment]
ロジカルには仰っている解決策が正しいように感じます。
しかし、私の環境において提示された変更を行うと下記のようなエラーが出て動かなくなります。
![clipboard02](https://cloud.githubusercontent.com/assets/5708932/11711814/794eec58-9f6c-11e5-9a5a-2cfdaf91f9db.jpg)

どうやら、非同期処理の完了を待てていないことが原因で chdir の待ち合わせがうまくいっていないように見受けられます。

少々追加調査します。

**Comment by Hiroyuki-Anzai** [comment]
こちらでも調査したところ、以下によって成功・失敗の違いがでました。
原因までは追っていませんが、役立つ情報であればと思いコメントいたします。

前提：同環境で2つの方法で実行
- Windows の コマンドプロンプト：失敗
- Git Bash：成功

**Comment by ahirun0426** [comment]
なるほどありがとうございます。
確かに私は Git Bash でのみ試してみていました。
Windows command prompt での再現試験＆問題回避法を模索してみます。

**Comment by ahirun0426** [comment]
これはどうやら windows command prompt と Git Bash の環境変数の持ち方の違いが原因で発生しているようですね。

cordova-lib/src/cordova/utils.js:130 において

```
        origCwd = process.env.PWD || process.cwd();
```

という記述があります。

Windows command prompt では process.env.PWD は undefined のため、process.cwd() が有効になりますが、Git Bash では PWD 環境変数が定義されており、こちらが優先されます。

このコードは cordova-lib 中から npm module として登録されている plugin をインストールしようとする際に fixRelativePath()を通じてコールされます。 
Git Bash の場合は yo を実行した path が PWD 環境変数に保存されているため、npm がこの path の直下においてある plugin を発見できます。
Windows command prompt の場合は PWD 環境変数が存在しないので、 process.cwd() の値を用いるため、npm は {pluginname}_TestBed 以下を探索するため plugin が見つからない。というのが報告されたエラーの原因のようです。

これは cordova-lib そのものの設計思想に依拠するものですので、generator-cordova-plugin-devbed 側での回避が必要ですね。

cordova.plugin('add') に渡す plugin 名をフルパスにすることで修正可能と思います。
修正 version を作成したいと思いますのでお待ちください。

**Comment by ahirun0426** [comment]
0.2.1 のリリースにて対処できたものと思います。

Close しますが、問題が残っているようでしたらコメントをお願いいたします。
